export default {
  grantType: 'password',
  clientId: 'vXlJ6ENTEnyme1j3mSIBmY8zSqNExXGXvLGaFAjh_oU',
  clientSecret: 'eYylaawmOukDyUI2cB9iR0oKKuUIsi7ix_XIMz3K6fY',
  BASE_URL: 'http://localhost',
  PORT: '3000',
  USER_AUTH_PATH: '/oauth/token',
  USER_LOGOUT_PATH: '/oauth/revoke',
  USER_REGISTRATION_PATH: '/api/users',
  APARTMENTS_PATH: '/api/apartments',
  NEW_APARTMENT_PATH: '/api/apartments',
  DESTROY_APARTMENT_PATH: '/api/apartments',
  RESERVATIONS_PATH: '/api/reservations',
  NEW_RESERVATION_PATH: '/api/reservations',
  DESTROY_RESERVATION_PATH: '/api/reservations',
};
